### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by liyingluo999** [MatthieuStigler/Misconometrics#3]
Hello Matthieu,

Thank you for sharing the code. I ran the following code 
dec_covar(object = model_full_1, var_main = "Education")
and got an error message:
 Error in data.frame(term = names(co), estimate = unname(co), stringsAsFactors = FALSE) : 
  arguments imply differing number of rows: 0, 2 

Any idea? Thanks!

Best,
Liying

**Comment by MatthieuStigler** [comment]
Can you please provide a reprex: https://www.tidyverse.org/help/

**Comment by liyingluo999** [comment]
![Rplot](https://user-images.githubusercontent.com/54556144/107441335-12d5af80-6b03-11eb-9501-a8cf3ac87b2e.png)

**Comment by liyingluo999** [comment]
Hi Matthieu,

I read over the conversations that you had with Lisa, which suggested that the error may have something to do with the dependent packages. I updated all packages including dplyr and data.table, and then the code runs without complaining. Thank you!

**Comment by MatthieuStigler** [comment]
great, any idea about the versions you had before, for further reference?

**Comment by liyingluo999** [comment]
sorry no idea; I should have kept track of it. I feel that the key is to manually update the data.table and the dplyr packages.
