### ISSUE TITLE
plm speed-up (from version 2.4-0, optional)

### ISSUE THREAD

**Issue by tappek** [MatthieuStigler/Misconometrics#5]
Hi, this is a three year old repository but I would like to make you aware of a fairly new option to run plm in fast mode: set `options("plm.fast" = TRUE)` is possible from plm version 2.4-0 on (see the NEWS file of the package). The current development version 2.4-1.99999 brings more speed-ups (in optional fast mode and in regular mode) https://r-forge.r-project.org/R/?group_id=406.

**Comment by MatthieuStigler** [comment]
oh thanks for letting me know!
