### ISSUE TITLE
Difficulty importing Gelbach_decompo/dec.covar.R script

### ISSUE THREAD

**Issue by DianaNaehrig** [MatthieuStigler/Misconometrics#6]
Hi Matthieu

I just came across your script for Gelbach decomposition and importance of predictor variables, and would love to use the dec_covar and plot_dec functions on my lm () regression, but I cannot import it into R studio.

I'm using devtools, usethis, githubinstall libraries. 
I tried the following command:
install.packages("https://raw.githubusercontent.com/MatthieuStigler/Misconometrics/master/Gelbach_decompo/dec_covar.R"). This returned the warning that this package is not available for this version of R. I am using version 4.0.4 "Lost Library Book".

Several variations of the command:
install_github("MatthieuStigler/Misconometrics/master/Gelbach_decompo/dec_covar.R") aren't giving me any joy either.

Is the problem that this is not a package, but a script? If so, how do I load the script into R studio, please?

Many thanks and kind regards, Diana

**Comment by MatthieuStigler** [comment]
Hi Diana

Sorry for the slow response. Yes indeed, it is only a script, not  a
package, so you can download according to the instructions in the Readme
<https://github.com/MatthieuStigler/Misconometrics/tree/master/Gelbach_decompo>
:

devtools::source_url("https://raw.githubusercontent.com/MatthieuStigler/Misconometrics/master/Gelbach_decompo/dec_covar.R")

 Also, if you use it for research, I would greatly appreciate it if you can
cite the work, you will find the citation in the same readme page.

Let me know if you have any further questions.

Best,
Matthieu



Le mer. 27 avr. 2022 à 23:22, DianaNaehrig ***@***.***> a
écrit :

**Comment by DianaNaehrig** [comment]
Hi Matthieu,

I’ve been meaning to thank you for your kind response and instructions on how to import the script.

The code performs well on the practice data set (swiss), but for some reason my dataframe keeps tripping the code. I suspect the issue has to do with base r and tidyverse….? Anyways, when I get it to run properly, and if I end up publishing this, I will certainly cite your work.

Many thanks and kind regards,
Diana

From: Matthieu ***@***.***>
Date: Tuesday, 3 May 2022 at 00:59
To: MatthieuStigler/Misconometrics ***@***.***>
Cc: Diana Naehrig ***@***.***>, Author ***@***.***>
Subject: Re: [MatthieuStigler/Misconometrics] Difficulty importing Gelbach_decompo/dec.covar.R script (Issue #6)
Hi Diana

Sorry for the slow response. Yes indeed, it is only a script, not a
package, so you can download according to the instructions in the Readme
<https://github.com/MatthieuStigler/Misconometrics/tree/master/Gelbach_decompo>
:

devtools::source_url("https://raw.githubusercontent.com/MatthieuStigler/Misconometrics/master/Gelbach_decompo/dec_covar.R")

Also, if you use it for research, I would greatly appreciate it if you can
cite the work, you will find the citation in the same readme page.

Let me know if you have any further questions.

Best,
Matthieu



Le mer. 27 avr. 2022 à 23:22, DianaNaehrig ***@***.***> a
écrit :

**Comment by MatthieuStigler** [comment]
> I suspect the issue has to do with base r and tidyverse….?

hard to tell. Try to see where the problem comes from, and if it is with the code itself, share a reproducible minimal example  ([How to make a great R reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example))

**Comment by DianaNaehrig** [comment]
Thank you.
